---
title: 'Course Project: Shiny Application and Reproducible Pitch'
author: "Amir Ali Khan"
date: "November 9,2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About the Course Project

This application is based on the course project of statistical inference class of the data science specialisation.

In this application, we are using data from world bank, it used data about the United States of America from 1960 to 2012, and what this is actually obtaining for us is the fertility rate of the US between these two dates.

## How to use the application

In this application, user can select date range from 1960 to 2012. user can use slider to select the months for forcast.
The user can can remove certain series from the visualization by selecting it, so if user don't want to see the confidence level anymore, he could remove that.

Additional Help menu available for "How to use" application.

## Output of the application

Attractive interactive chart is shwoing the time series data, and then used a forecast function to forecast forward three years. As you hover over, you have some information, you have the fertility rate after that specific point in time.It also has some additional information in the tool tip.

## Links of the application

The application is running on (https://khanamirali.shinyapps.io/DDP_W4_CP/)

ui.R, and Server.R Code in my github repository (https://github.com/khanamirali/Shiny_Application_Reproducible_Pitch)


